backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: '/img'

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'content/pages/home.md'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Background Image, name: background-img, widget: image }